# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99ddfe89910f9d817f7f08d2d2eb9d034a720e8569a7cb39cc06afe1f29ade26bf8a6979a3705b668192aff9c2b6628ce71ccce30ca89caee06414b10e730b54

test:
  secret_key_base: 8395c21c0124e303c735ebd0e69e9a3304c430a3e65dea8bbba16a39a04f495654acd6619f46c7c7822cefa0862a403adba901f4bc270f468d72696876f5aefe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
